library(jsonlite)
library(dplyr)
url <- '/tmp/out.json'
document <- fromJSON(txt=url)
a <- data.frame(document$'?dbpwork', document$'?o1')
a <- na.omit(a)
colnames(a) <- c('subject1','object1')
b <- data.frame(document$'?works', document$'?o2')
b <- na.omit(b)
colnames(b) <- c('subject2','object1')
diff <- anti_join(a, b, by='object1')
m <- merge(a,b, by.x='object1')
toJSON(m, pretty=TRUE)
toJSON(diff, pretty=TRUE)
