library(jsonlite)
library(dplyr)
library(rio)
url <- '/tmp/out.json'
document <- fromJSON(txt=url)
a <- data.frame(document$'?dbr', document$'?o1')
a <- na.omit(a)
colnames(a) <- c('subject1','object1')
b <- data.frame(document$'?wde', document$'?o2')
b <- na.omit(b)
colnames(b) <- c('subject2','object1')
diff <- anti_join(b, a, by='object1')
export(diff, '/tmp/diff_s2-s1.csv')
